apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: superapi-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: superapi
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50