---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: super-api
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/super-api
      sourceRef:
        kind: GitRepository
        name: super-api
  interval: 1m0s
  targetNamespace: default

